## File handling in python
    -reading
    -writing
    -appending

### basic method
 - without with 

In [1]:
fp = open("example.txt",'w')
content=["line 1","line 2","line 3","line 4","line 5"]
for line in content:
    fp.write(line+"\n")
fp.close()
fp.closed

True

In [2]:
fp = open("example.txt",'r')
content=fp.read()
print(content)
fp.close()

line 1
line 2
line 3
line 4
line 5



In [3]:
fp = open("example.txt",'r')
content=fp.readlines()
print(content)
fp.close()

['line 1\n', 'line 2\n', 'line 3\n', 'line 4\n', 'line 5\n']


In [4]:
fp = open("example.txt",'r')
content=fp.readlines()
print(content)
content=[i.rstrip("\n") for i in content]
print(content)
fp.close()

['line 1\n', 'line 2\n', 'line 3\n', 'line 4\n', 'line 5\n']
['line 1', 'line 2', 'line 3', 'line 4', 'line 5']


In [5]:
fp = open("example.txt",'r')
for line in fp:
    print(line,end='')
fp.close()

line 1
line 2
line 3
line 4
line 5


### With method
    - with method takes care of closing the file

In [6]:
with open("example.txt",'r') as fp:
    for line in fp:
        print(line,end='')

line 1
line 2
line 3
line 4
line 5


In [7]:
with open("example.txt",'a+') as fp:
    fp.write("line 5 \n")
    fp.seek(0)
    for line in fp:
        print(line,end='')

line 1
line 2
line 3
line 4
line 5
line 5 


#### if we have a large file it will take more memory in RAM when we read it so we can use "read( size of character you want to read )"

In [9]:
with open("example.txt",'r') as fp:
    sizeofread=3
    content=fp.read(sizeofread)
    while len(content) > 0:
        print(content,end='')
        content=fp.read(sizeofread)

line 1
line 2
line 3
line 4
line 5
line 5 


In [10]:
import os
print(os.getcwd())

C:\Users\upendra


In [11]:
with open("example.txt",'r') as fp:
    sizeofread=10
    content=fp.read(sizeofread)
    while len(content) > 0:
        print(content,end='')
        content=fp.read(sizeofread)

line 1
line 2
line 3
line 4
line 5
line 5 


In [12]:
with open("example.txt",'r') as rf:
    with open("example_copy.txt",'w') as wf:
        for line in rf:
            wf.write(line)
    


#### - write mode always overwrite on the privious file


### for other then txt file we use binary to read and write or codec and UTF-8 will give the error

In [15]:
with open("Desktop/File handling.txt",'rb') as rf:
    with open("Desktop/File handling_copy.txt",'wb') as wf:
        for line in rf:
            wf.write(line)

In [17]:
with open("Desktop/TensorFlow for Computer Vision - Full Tutorial for Beginners.mp4",'rb') as rf:
    with open("Desktop/TensorFlow for Computer Vision - Full Tutorial for Beginners_copy.mp4",'wb') as wf:
        for line in rf:
            wf.write(line)

### file size is big so we can use the chunck or small size at a time to write in another file

In [18]:
import sys
with open("Desktop/TensorFlow for Computer Vision - Full Tutorial for Beginners.mp4",'rb') as rf:
    with open("Desktop/TensorFlow for Computer Vision - Full Tutorial for Beginners_copy.mp4",'wb') as wf:
        sizetoread = 2048
        content = rf.read(sizetoread)
        print(sys.getsizeof(content))
        while len(content) > 0:
            wf.write(content)
            content = rf.read(sizetoread)

2081


### we can use tell() to get the location of the pointer

In [19]:
with open("example.txt",'r') as fp:
    print(fp.tell())
    sizetoread = 3
    content = fp.read(sizetoread)
    print(content)
    print(fp.tell())


0
lin
3


In [20]:
with open("example.txt",'r') as fp:
    sizeofread=10
    content=fp.read(sizeofread)
    while len(content) > 0:
        print(content,end='')
        content=fp.read(sizeofread)


line 1
line 2
line 3
line 4
line 5
line 5 


In [22]:
import numpy as np
np_data = np.loadtxt(r"example2.txt" , dtype = 'int')
print(np_data)
print(np_data.dtype)

[11 12 13 14 15 16 17]
int32


In [26]:
import numpy as np
np_data = np.loadtxt(r"example2.txt" , dtype = 'int')
print(np_data)
print(np_data.dtype)
np_data = np_data*2
np.savetxt(r"updated_example2.txt", np_data)
np_data = np.loadtxt(r"updated_example2.txt" , dtype = 'int')
print(np_data)
print(np_data.dtype)

[11 12 13 14 15 16 17]
int32
[22 24 26 28 30 32 34]
int32


In [29]:
# Deleting a file
import os
os.remove("example.txt")