# Numpy
Numpy is 50x faster then traditional python lists because NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines.

In [1]:
import numpy as np
n = [1, 2, 3, 4, 5, 6]
n = np.array(n)
n

array([1, 2, 3, 4, 5, 6])

In [2]:
# Datatype have to be same
marks = [12,2.3,21,a,1.5]
np_marks = np.array(marks)
print(np_marks)
print(type(np_marks))

NameError: name 'a' is not defined

In [3]:
marks = ['a', 'b', 'c', 'd', 'e', 'f']
np_marks = np.array(marks)
print(np_marks)
print(type(np_marks))

['a' 'b' 'c' 'd' 'e' 'f']
<class 'numpy.ndarray'>


In [4]:
marks = [12,23,21,5,15]
np_marks = np.array(marks)
print(np_marks)
print(type(np_marks))
print(np_marks.dtype)

[12 23 21  5 15]
<class 'numpy.ndarray'>
int32


In [8]:
print(np_marks.size)
print(np_marks.ndim)

5
1


In [9]:
# for size in bytes of members 
np_marks.itemsize

4

In [10]:
data = input().split()
print("data = ",data)
data = [int(n) for n in data]
print(data)

234 235 4 5436 54 765 86 867 98 0890 890 8 976 8787
data =  ['234', '235', '4', '5436', '54', '765', '86', '867', '98', '0890', '890', '8', '976', '8787']
[234, 235, 4, 5436, 54, 765, 86, 867, 98, 890, 890, 8, 976, 8787]


In [11]:
data= input().split()
np_data = np.array(data)
np_converted = np_data.astype('int')
print(np_data , np_data.dtype)
print(np_converted , np_converted.dtype)
np_converted.itemsize

343654 765 87 94 64 6 3 2 5 135 231235 233
['343654' '765' '87' '94' '64' '6' '3' '2' '5' '135' '231235' '233'] <U6
[343654    765     87     94     64      6      3      2      5    135
 231235    233] int32


4

In [12]:
marks = [128,32768,2147483648,2147483648]
np_marks = np.array(marks , dtype='float64')
print(np_marks)
print(np_marks.dtype)

[1.28000000e+02 3.27680000e+04 2.14748365e+09 2.14748365e+09]
float64


In [13]:
# accessing elements
data=["abc", "defgh", "ijkl", "mnopqrst"]
np_data = np.array(data)
print(np_data[-1])
print(np_data[-2])

mnopqrst
ijkl


In [14]:
#shallow copy   -  change will show into copy
a = [12,23,34,45,56]
b = a
print("a : " , a)
print("b : " , b)
a[0] = 78
a[1] = 89
print("a : " , a)
print("b : " , b)
b[0] = 1
b[1] = 2
print("a : ",a)
print("b :",b)

a :  [12, 23, 34, 45, 56]
b :  [12, 23, 34, 45, 56]
a :  [78, 89, 34, 45, 56]
b :  [78, 89, 34, 45, 56]
a :  [1, 2, 34, 45, 56]
b : [1, 2, 34, 45, 56]


In [15]:
#deep copy
a = [12,23,34,45,56]
c = a[:3]
print("a : " , a)
print("c : " , c)
a[0] = 78
a[1] = 89
print("a : " , a)
print("c : " , c)

a :  [12, 23, 34, 45, 56]
c :  [12, 23, 34]
a :  [78, 89, 34, 45, 56]
c :  [12, 23, 34]


In [16]:
#shallow copy of numpy array
a =np.array([12,23,34,45,56])
c = a[:3]
print("a : " , a)
print("c : " , c)
a[0] = 78
a[1] = 89
print("a : " , a)
print("c : " , c)

a :  [12 23 34 45 56]
c :  [12 23 34]
a :  [78 89 34 45 56]
c :  [78 89 34]


In [17]:
#deep copy of numpy array
a = np.array([12,23,34,45,56])
c = np.copy(a[:3])
print("a : " , a)
print("c : " , c)
a[0] = 78
a[1] = 89
print("a : " , a)
print("c : " , c)

a :  [12 23 34 45 56]
c :  [12 23 34]
a :  [78 89 34 45 56]
c :  [12 23 34]


In [18]:
salary = [200,320,250,400]
bonus = 10
bonus_salary = [(i+bonus) for i in salary]
print(bonus_salary)

[210, 330, 260, 410]


### Broadcasting

In [19]:
salary = [200,320,250,400]
np_salary = np.array(salary)
np_bonussalary = np_salary+10
print(np_bonussalary)
#Numpy Array (any operator) scalar value==> it will apply to all it is broadcsting

[210 330 260 410]


In [20]:
salary = [200,320,250,400]
np_salary = np.array(salary)
np_bonussalary = np_salary+((np_salary)*0.1)
print(np_bonussalary)

[220. 352. 275. 440.]


### VECTORIZATION

In [21]:
np_first = np.array([200,320,250,400])
np_second = np.array([200,320,250,400])
np_result = np_first+np_second                       #vectorization
print(np_result)

[400 640 500 800]


In [22]:
# for vectorization size have to be same
np_first = np.array([200,320,250,400,565])
np_second = np.array([200,320,250,400])
np_result = np_first+np_second                      
print(np_result)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [23]:
a = [5, 6, 7]
b = [5, 6, 7]
print( a == b )

True


In [24]:
a = [5, 6, 7]
b = [5, 6, 7]
b is a

False

In [25]:
a = [5, 6, 7]
b = [5, 6, 7]
c = a
print( id(a) == id(b))
print( id(a) == id(c))

False
True


In [26]:
np_a = np.array([5 ,6 ,7])
np_b = np.array([5, 6, 7])
print(np_a == np_b)
print(np_a is np_b)
id(np_a)==id(np_b)

[ True  True  True]
False


False

In [27]:
np_a = np.array([5, 6, 8])
np_b = np.array([5, 6, 7])
print(np_a == np_b)
print(np_a is np_b)
id(np_a) == id(np_b)

[ True  True False]
False


False

In [28]:
p1 = np.array([6,4,3,6,7])
p2 = np.array([5,5,8,6,7])
p1 > p2

array([ True, False, False, False, False])

In [29]:
p1 = [5, 6, 7, 8, 9]
p2 = [6, 1, 2, 3, 4]
p1 > p2
#in list it will check for only for 1st element

False

In [30]:
marks = [23, 18, 29, 40, 15, 12]
li = [i for i in marks if i>20]
print(li)

[23, 29, 40]


In [31]:
np_marks = np.array([23, 18, 29, 40, 15, 12])
passedBool = (np_marks >= 20)
print(passedBool)
np_marks[passedBool]

[ True False  True  True False False]


array([23, 29, 40])

In [32]:
np_marks = np.array([23, 18, 29, 40, 15, 12])
np_marks[np_marks > 20]

array([23, 29, 40])

In [33]:
np_marks = np.array([23, 18, 29, 40, 15, 12, 45, 29, 35])
passedBool = np_marks[(np_marks >= 20) & (np_marks <= 40)]
passedBool

array([23, 29, 40, 29, 35])

In [34]:
# lets assume more then 15 is good score
np_marksAptitude = np.array([12, 18, 20, 18, 21])
np_marksTechnical = np.array([18, 17, 20, 14, 22])

goodInAtleastOne = ((np_marksAptitude >= 15) |  (np_marksTechnical >= 15))

print(goodInAtleastOne)

goodInBoth = ((np_marksAptitude >= 15) &  (np_marksTechnical >= 15))

print(goodInBoth)

[ True  True  True  True  True]
[False  True  True False  True]


In [35]:
np_marksAptitude = np.array([12,18,20,18,21])
np_marksTechnical = np.array([18,17,20,14,22])

c1 = (np_marksAptitude >= 15)

c2 = (np_marksTechnical >= 15)

print("good in both ",c1 & c2)
print("good in only one ",c1 ^ c2)
print("good in atlest one ",c1 | c2)

good in both  [False  True  True False  True]
good in only one  [ True False False  True False]
good in atlest one  [ True  True  True  True  True]


In [36]:
a = [12, 13, 4, 5]
np_a = np.array(a)

print(sum(np_a))        #list sum

print(np_a.sum())

print(np.sum(np_a))    #numpy sum

# 1. numpy functions are faster
# 2. numpy functions can be used with multidimensional arrays

34
34
34


In [37]:
a = [12, 1, 3, 14, 29, 23, 6]
b = a.index(max(a))
print(b)

4


In [38]:
np_a = np.array(a)
print(np.argmax(np_a))                             #largest element index
print(np.argmin(np_a))                            #smallest element index

4
1


In [39]:
# average of np array
a = [2, 5, 1, 6, 14, 7]
np_a = np.array(a)
avg = np.sum(np_a)/len(np_a)
print(avg)

5.833333333333333


In [40]:
a = [1, 2, 2, 2, 1]
np_a = np.array(a)

avg = np.mean(np_a)
print(avg)                      #average

med = np.median(np_a)
print(med)                      #median

stdd = np.std(np_a)
print(stdd)                     #standard deviation

1.6
2.0
0.4898979485566356


In [41]:
minMarks = 20
np_marks = np.array( [23,20, 34, 42, 29, 18, 12, 34])
np_pass = np_marks[np_marks >=20]
print(len(np_pass))

6


In [42]:
minMarks = 20
np_marks = np.array( [23,20, 34, 42, 29, 18, 12, 34])
(np_marks >= 20).sum()

6

In [43]:
minMarks = 20
np_marks = np.array( [23,20, 34, 42, 29, 18, 12, 34])
print("pass" if (np_marks >= minMarks).all() else "fail")

fail


In [44]:
minMarks = 20
np_marks = np.array( [23,20, 34, 42, 29, 20, 20, 34])
print("pass" if (np_marks >= minMarks).all() else "fail")

pass


In [45]:
np_marks = np.array( [23,20, 34, 42, 29, 18, 12, 34])
np_marks = np.append(np_marks,34)          #we have to receive it in an array or list because it is not changing the argument
np_marks

array([23, 20, 34, 42, 29, 18, 12, 34, 34])

In [46]:
# append and delete
np_marks = np.array( [23,20, 34, 42, 29, 18, 12, 34])
np_newarray = np.append(np_marks,[23,45,7])    #we have to receive it in an array or list because it is not changing the argument
np_newarray

array([23, 20, 34, 42, 29, 18, 12, 34, 23, 45,  7])

In [47]:
print(np.delete(np_marks,1))
print(np_marks)

[23 34 42 29 18 12 34]
[23 20 34 42 29 18 12 34]


In [48]:
np_marks = np.array([11,12,13,14,1,2])
np_newmarks = np.array(np.delete(np_marks,range(0,4)))
print(np_marks)
print(np_newmarks)

[11 12 13 14  1  2]
[1 2]


In [49]:
student1 = [12, 23, 34]
student2 = [21, 32, 43]
student3 = [14, 25, 36]
student4 = [19, 17, 21]
marksList = [student1, student2, student3, student4]
print( marksList )
for ele in marksList :
    print(sum(ele))

[[12, 23, 34], [21, 32, 43], [14, 25, 36], [19, 17, 21]]
69
96
75
57


In [50]:
student1 = [12, 23, 34]
student2 = [21, 32, 43]
student3 = [14, 25, 36]
student4 = [19, 17, 21]
marksList = [student1, student2, student3, student4]
add = 0
print("marksList :", marksList )
for ele in marksList :
    print(sum(ele))
print( marksList )
for ele in marksList :
    add = sum(ele)+add
print("Addition of all:",add)

marksList : [[12, 23, 34], [21, 32, 43], [14, 25, 36], [19, 17, 21]]
69
96
75
57
[[12, 23, 34], [21, 32, 43], [14, 25, 36], [19, 17, 21]]
Addition of all: 297


In [51]:
student1 = [12, 23, 34]
student2 = [21, 32, 43]
student3 = [14, 25, 36]
student4 = [19, 17, 21]
marksList = [student1, student2, student3, student4]
add = 0
rows = len(marksList)
print(rows)
cols = len(marksList[0])
print(cols)

c = 0
for ri in range(rows):
    for ci in range(cols):
        if ci==c:
            add = add+marksList[ri][ci]
print(add,end=' ')

4
3
66 

In [52]:
np_marksList=np.array(marksList)
print(marksList)
print(np_marksList)

[[12, 23, 34], [21, 32, 43], [14, 25, 36], [19, 17, 21]]
[[12 23 34]
 [21 32 43]
 [14 25 36]
 [19 17 21]]


In [53]:
rows = len(np_marksList)
print(rows)
cols = len(np_marksList[0])
print(cols)
add=0
c = 0
for ri in range(rows):
    for ci in range(cols):
        if ci==c:
            add=add+np_marksList[ri][ci]
print(add)

4
3
66


In [54]:
print(np.sum(np_marksList))

297


In [55]:
print(np.delete(np_marksList,5))

[12 23 34 21 32 14 25 36 19 17 21]


In [56]:
np_a = np.array([1,2,3,4,5,6,7,8,9,10])
print(np_a)
print( np_a.reshape((5, 2))  )
print( np_a.reshape((2 , 5)) )

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [57]:
np_a = np.arange(10)
print(np_a)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
np_a=np.arange(2,10)
print(np_a)
np_a=np.arange(1,20,3)
print(np_a)

[2 3 4 5 6 7 8 9]
[ 1  4  7 10 13 16 19]


In [59]:
#x=range(1,10,0.5)
#print(x)
#step size float is not avaliable in range fun
np_a=np.arange(1,20,0.5)
print(np_a)
np_a=np.arange(10, step = 0.5)
print(np_a)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [60]:
print(np.ones(5))
print(np.ones((2,3)) )
print(np.zeros(5))
print(np.zeros((2,3)) )
print(np.eye(5))                  #for digonal 1 matrix

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [61]:
np_mat = np.arange(12).reshape(3,4)
print(np_mat)
np_mat+2                         #vectorization

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [62]:
np_mat = np.arange(12).reshape(3,4)
print(np_mat)
np_mat+[1,2,0,5]                  #adding in column 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 1,  3,  2,  8],
       [ 5,  7,  6, 12],
       [ 9, 11, 10, 16]])

In [63]:
#adding two matrix
np_mat1=np.arange(12).reshape(3,4)
np_mat2=np.arange(1,13).reshape(3,4)
print(np_mat1)
print(np_mat2)
print("---------------")
print(np_mat1 + np_mat2 )                             # shapes have to be same

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------------
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]


In [64]:
# for substarcting is same as addition
# for multiplication (a * b) (c * d) then b==c and result is (a * d)

In [65]:
np_mat1 = np.arange(9).reshape(3,3)
np_mat2 = np.arange(1,10).reshape(3,3)
print(np_mat1)
print(np_mat2)
print("-------element wise multiplication--------")
print(np_mat1 * np_mat2 )  
print("-------matrix mathwise multiplication--------")
print(np_mat1 .dot(np_mat2)) 
print("-------matrix mathwise multiplication--------")
print(np_mat1 @ np_mat2) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------element wise multiplication--------
[[ 0  2  6]
 [12 20 30]
 [42 56 72]]
-------matrix mathwise multiplication--------
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
-------matrix mathwise multiplication--------
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]


In [66]:
np_mat1 = np.arange(12).reshape(3,4)
np_mat2 = np.arange(20).reshape(4,5)
print(np_mat1)
print(np_mat2)
#print("-------element wise multiplication--------")            # for element wise size have to be same
#print(np_mat1 * np_mat2 )  
print("-------matrix mathwise multiplication--------")
print(np_mat1 .dot(np_mat2)) 
print("-------matrix mathwise multiplication--------")
print(np_mat1 @ np_mat2) 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------matrix mathwise multiplication--------
[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]]
-------matrix mathwise multiplication--------
[[ 70  76  82  88  94]
 [190 212 234 256 278]
 [310 348 386 424 462]]


In [67]:
# accessing the element in matrix
import numpy as np
np_a = np.arange(20).reshape(4,5)
print(np_a)
ri = int(input("row index :"))
ci = int(input("col inddex :"))
f = np_a[ri][ci]
s = np_a[ri , ci]
print(f)
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
row index :1
col inddex :1
6
6


In [68]:
print(np_a[ : 3 , : ])      #first 3 rows
print(np_a[ :  , : 2 ])      #first 2 cols                          #this is not possible with double brackets 
print(np_a[1:3 , 1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]]
[[ 6  7  8]
 [11 12 13]]


In [69]:
import random 
#dir(random)
# randint, random , seed
help(random.random)

Help on built-in function random:

random(...) method of random.Random instance
    random() -> x in the interval [0, 1).



In [70]:
random.random()

0.37314612288291826

In [71]:
x = random.random()
y = x*100
print(x)
print(y)
print(int(y))

0.8362607636040285
83.62607636040285
83


In [72]:
help(random.randint)

Help on method randint in module random:

randint(a, b) method of random.Random instance
    Return random integer in range [a, b], including both end points.



In [73]:
x = random.randint(-50,1)
print(x)

-26


In [74]:
for i in range(10):
    print(random.randint(-50,100))

87
-28
-39
50
-17
44
-33
12
29
21


In [75]:
help(random.seed)

Help on method seed in module random:

seed(a=None, version=2) method of random.Random instance
    Initialize internal state from hashable object.
    
    None or no argument seeds from current time or from an operating
    system specific randomness source if available.
    
    If *a* is an int, all bits are used.
    
    For version 2 (the default), all of the bits are used if *a* is a str,
    bytes, or bytearray.  For version 1 (provided for reproducing random
    sequences from older versions of Python), the algorithm for str and
    bytes generates a narrower range of seeds.



In [2]:
import random
random.seed(10)
for i in range(10):
    print(random.randint(0,10))

9
0
6
7
9
0
3
7
7
4


In [77]:
from random import randint

def generateRandom(start, end , n):
    a = []
    for i in range(n):
        a.append( randint(start,end) )
    return np.array(a) 

In [78]:
np_a = generateRandom(1,20,10)
np_b = generateRandom(1,20,10)
print(np_a)
print(np_b)

[ 6  2 17 16 11  3  8 12  2 14]
[ 5 20 12 13 14 10  9 15  6 10]


In [79]:
np_a = np_a.reshape((2,5))
np_b = np_b.reshape((2,5))
print(np_a)
print(np_b)

[[ 6  2 17 16 11]
 [ 3  8 12  2 14]]
[[ 5 20 12 13 14]
 [10  9 15  6 10]]


In [80]:
print("Sum of entire matrix : ", np.sum(np_a))  #
print("Column-wise sum")
print(np.sum(np_a, axis = 0))
print("Row-wise sum")
print(np.sum(np_a, axis = 1))

Sum of entire matrix :  91
Column-wise sum
[ 9 10 29 18 25]
Row-wise sum
[52 39]


In [81]:
print("Column-wise sum")
print(np_a.sum(axis = 0))
print("Row-wise sum")
print(np_a.sum(axis = 1))

Column-wise sum
[ 9 10 29 18 25]
Row-wise sum
[52 39]


In [82]:
print("Column-wise max")
print(np.max(np_a, axis = 0))
print("Row-wise max")
print(np.max(np_a, axis = 1))

Column-wise max
[ 6  8 17 16 14]
Row-wise max
[17 14]


In [83]:
print("Column-wise min")
print(np.min(np_a, axis = 0))
print("Row-wise min")
print(np.min(np_a, axis = 1))

Column-wise min
[ 3  2 12  2 11]
Row-wise min
[2 2]


In [84]:
a=[[1,2],[3,4]]
b=[[5,6],[7,8]]
a + b

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [85]:
print(np_a)
print(np_b)
print("Stacking the matrics in vertical stack")
print(np.vstack((np_a,np_b)))
print("Stacking the matrics in horizontal stack")
print(np.hstack((np_a,np_b)))

[[ 6  2 17 16 11]
 [ 3  8 12  2 14]]
[[ 5 20 12 13 14]
 [10  9 15  6 10]]
Stacking the matrics in vertical stack
[[ 6  2 17 16 11]
 [ 3  8 12  2 14]
 [ 5 20 12 13 14]
 [10  9 15  6 10]]
Stacking the matrics in horizontal stack
[[ 6  2 17 16 11  5 20 12 13 14]
 [ 3  8 12  2 14 10  9 15  6 10]]


In [86]:
np_c = generateRandom(1,20,10)
np_c = np_c.reshape((2,5))
print(np_a)
print(np_b)
print(np_c)
print("vertical stack \n")
print(np.vstack((np_a,np_b,np_c)))
print("horizontal stack \n")
print(np.hstack((np_a,np_b,np_c)))

[[ 6  2 17 16 11]
 [ 3  8 12  2 14]]
[[ 5 20 12 13 14]
 [10  9 15  6 10]]
[[12  5 15  8 15]
 [20 13  2 19  1]]
vertical stack 

[[ 6  2 17 16 11]
 [ 3  8 12  2 14]
 [ 5 20 12 13 14]
 [10  9 15  6 10]
 [12  5 15  8 15]
 [20 13  2 19  1]]
horizontal stack 

[[ 6  2 17 16 11  5 20 12 13 14 12  5 15  8 15]
 [ 3  8 12  2 14 10  9 15  6 10 20 13  2 19  1]]


In [87]:
np_a = generateRandom(1,20,12)
np_a = np_a.reshape((4,3))
np_b = generateRandom(1,20,9)
np_b = np_b.reshape((3,3))
np_c = generateRandom(1,20,15)
np_c = np_c.reshape((5,3))
print(np_a)
print(np_b)
print(np_c)
print("vertical stack \n")
print(np.vstack((np_a,np_b,np_c)))

[[ 8  5  7]
 [10 18 12]
 [ 8 11 18]
 [15 14 16]]
[[ 3 19 11]
 [17  6  8]
 [14  8  2]]
[[ 2 16 10]
 [20  3 18]
 [ 3  5 13]
 [19 12 20]
 [ 5  4  4]]
vertical stack 

[[ 8  5  7]
 [10 18 12]
 [ 8 11 18]
 [15 14 16]
 [ 3 19 11]
 [17  6  8]
 [14  8  2]
 [ 2 16 10]
 [20  3 18]
 [ 3  5 13]
 [19 12 20]
 [ 5  4  4]]


In [89]:
np_a = generateRandom(1,20,12)
np_a = np_a.reshape((3,4))
np_b = generateRandom(1,20,9)
np_b = np_b.reshape((3,3))
np_c = generateRandom(1,20,15)
np_c = np_c.reshape((3,5))
print(np_a)
print(np_b)
print(np_c)
print("\n horizontal  stack \n")
print(np.hstack((np_a,np_b,np_c)))

[[ 6 13 16  8]
 [17  9 17 16]
 [20 16  3  6]]
[[16 15 13]
 [ 5 14 18]
 [19 12 18]]
[[13 16  6 18 15]
 [ 4 14  2  1 15]
 [18  3  2 12  3]]

 horizontal  stack 

[[ 6 13 16  8 16 15 13 13 16  6 18 15]
 [17  9 17 16  5 14 18  4 14  2  1 15]
 [20 16  3  6 19 12 18 18  3  2 12  3]]
